services:
  - type: web
    name: binance-alert-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: WEBHOOK_URL
        value: https://price-alert-roro.onrender.com
