services:
  - type: worker
    name: telegram-bot
    runtime: python
    repo: https://github.com/pjtdg2025/price-alert 
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
plan: free
